#!/bin/sh
set -e

case "$1" in
	configure)
		if [ -z "$2" ]; then
			addgroup --system docker
		fi
		;;
	abort-*)
		# How'd we get here??
		exit 1
		;;
	*)
		;;
esac

if [ -x "/etc/init.d/docker" ]; then
	update-rc.d docker defaults >/dev/null
	invoke-rc.d docker start || exit $?
fi
